parameters:
    presta_cms.block.carousel.class: Presta\CMSMediaBundle\Block\CarouselBlockService
    presta_cms.block.media.class: Presta\CMSMediaBundle\Block\MediaBlockService
    presta_cms.block.media_advanced.class: Presta\CMSMediaBundle\Block\MediaAdvancedBlockService
    presta_cms.block.gallery.class: Presta\CMSMediaBundle\Block\GalleryBlockService
    presta_cms.block.gallery_advanced.class: Presta\CMSMediaBundle\Block\GalleryAdvancedBlockService

services:
    presta_cms.block.carousel:
        class: %presta_cms.block.carousel.class%
        tags:
            - {name: sonata.block}
            - {name: presta_cms.block}
        arguments: [cms_core_editor, @templating,@service_container, @sonata.media.manager.media]
        calls:
            - [ setTranslator, [@translator] ]
            - [ setAdminPool, [@sonata.admin.pool]]
    presta_cms.block.media:
        class: %presta_cms.block.media.class%
        tags:
            - {name: sonata.block}
            - {name: presta_cms.block}
        arguments: [cms_core_editor, @templating,@service_container, @sonata.media.manager.media]
        calls:
            - [ setTranslator, [@translator] ]
            - [ setAdminPool, [@sonata.admin.pool]]
    presta_cms.block.media_advanced:
        class: %presta_cms.block.media_advanced.class%
        tags:
            - {name: sonata.block}
            - {name: presta_cms.block}
        arguments: [cms_core_editor, @templating,@service_container, @sonata.media.manager.media]
        calls:
            - [ setTranslator, [@translator] ]
            - [ setAdminPool, [@sonata.admin.pool]]
    presta_cms.block.gallery:
        class: %presta_cms.block.gallery.class%
        tags:
            - {name: sonata.block}
            - {name: presta_cms.block}
        arguments: [cms_core_editor, @templating,@service_container, @sonata.media.manager.media]
        calls:
            - [ setTranslator, [@translator] ]
            - [ setAdminPool, [@sonata.admin.pool]]
    presta_cms.block.gallery_advanced:
        class: %presta_cms.block.gallery_advanced.class%
        tags:
            - {name: sonata.block}
            - {name: presta_cms.block}
        arguments: [cms_core_editor, @templating,@service_container, @sonata.media.manager.media]
        calls:
            - [ setTranslator, [@translator] ]
            - [ setAdminPool, [@sonata.admin.pool]]