parameters:
#    presta_cms_media.example.class: Presta\CMSMediaBundle\Example

services:
    presta_cms.block.carousel:
        class: Presta\CMSMediaBundle\Block\CarouselBlockService
        tags:
            - {name: sonata.block}
            - {name: presta_cms.block}
        arguments: [cms_core_editor, @templating,@service_container, @sonata.media.manager.media]
        calls:
            - [ setTranslator, [@translator] ]
            - [ setContainer, [@service_container]]
    presta_cms.block.media:
        class: Presta\CMSMediaBundle\Block\MediaBlockService
        tags:
            - {name: sonata.block}
            - {name: presta_cms.block}
        arguments: [cms_core_editor, @templating,@service_container, @sonata.media.manager.media]
        calls:
            - [ setTranslator, [@translator] ]
            - [ setContainer, [@service_container]]
    presta_cms.block.media_advanced:
        class: Presta\CMSMediaBundle\Block\MediaAdvancedBlockService
        tags:
            - {name: sonata.block}
            - {name: presta_cms.block}
        arguments: [cms_core_editor, @templating,@service_container, @sonata.media.manager.media]
        calls:
            - [ setTranslator, [@translator] ]
            - [ setContainer, [@service_container]]
    presta_cms.block.gallery:
        class: Presta\CMSMediaBundle\Block\GalleryBlockService
        tags:
            - {name: sonata.block}
            - {name: presta_cms.block}
        arguments: [cms_core_editor, @templating,@service_container, @sonata.media.manager.media]
        calls:
            - [ setTranslator, [@translator] ]
            - [ setContainer, [@service_container]]
    presta_cms.block.gallery_advanced:
        class: Presta\CMSMediaBundle\Block\GalleryAdvancedBlockService
        tags:
            - {name: sonata.block}
            - {name: presta_cms.block}
        arguments: [cms_core_editor, @templating,@service_container, @sonata.media.manager.media]
        calls:
            - [ setTranslator, [@translator] ]
            - [ setContainer, [@service_container]]