language: php

php:
  - 5.3
  - 5.4
  - 5.4

before_script:
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs --ignore=/vendor/* --extensions=php --encoding=utf-8 --standard=PSR2 -np .


notifications:
  email: "nbastien@prestaconcept.net"
